### ISSUE TITLE
code seems to hardcode gcr.io URL

### ISSUE THREAD

**Issue by steren** [boardingparty/minecraft_gcp#1]
https://github.com/boardingparty/minecraft_gcp/blob/6b287c8a8fc5515a4f0945df174d3a6037676095/boardingparty/backend_gcp/app.json#L16

**Comment by tomlarkworthy** [comment]
I mostly fixed upstream (ie. the project, the tag), though the gcr.io domain remains (losing e.g. eu.gcr.io, option)

**Comment by tomlarkworthy** [comment]
yes maybe works outside of my account now (?)
